### ISSUE TITLE
not functioning

### ISSUE THREAD

**Issue by AmirhosseinDotZip** [Shresht7/PowerToysRun-SearchEngines#24]
the plugin isn't working for me, i run the command and it simply does nothing.

**Comment by Shresht7** [comment]
Huh, that's odd. Can you describe your problem in a little more detail?
Is it just that it doesn't open the browser? or does the plugin not load at all?

**Comment by AmirhosseinDotZip** [comment]
it is working now, it seems like it just needed a restart.

**Comment by Shresht7** [comment]
That's good to hear. Plugins are loaded at the start when PowerToys is being initialized, not while the process is running. That's why you need to restart the program.
